### ISSUE TITLE
riplit

### ISSUE THREAD

**Issue by ahmad19981** [DevelopersSupportAR/rexom#16]
TypeError: /home/runner/rexom-1/source/server/views/index.ejs:18
    16|             <img src="https://t4.ftcdn.net/jpg/03/03/86/25/240_F_303862557_fqPo9RFHohaJdV0cVqEeuQLsxk9qfUAA.jpg" style="margin-top: 100px; width: 250px; height: 250px; border-radius: 50%;">
    17|             <h1 class="display-3" style="margin-top: 30px;">re<b style="color: red;">X</b>om</h1>
 >> 18|             <button type="button" class="btn btn-primary btn-lg" onclick="location.href='https://discord.com/api/oauth2/authorize?client_id=<%= bot.user.id %>&permissions=6747975000&redirect_uri=<%= collback %>&scope=bot%20applications.commands'">Invite</button>
    19|             <% if (user && user.id) {%>
    20|                 <button type="button" class="btn btn-secondary btn-lg" onclick="location.href='/dashboard'">Dashboard</button>
    21|                 <% } else {%>

Cannot read properties of null (reading 'id')
    at eval ("/home/runner/rexom-1/source/server/views/index.ejs":13:35)
    at index (/home/runner/rexom-1/node_modules/ejs/lib/ejs.js:692:17)
    at tryHandleCache (/home/runner/rexom-1/node_modules/ejs/lib/ejs.js:272:36)
    at View.exports.renderFile [as engine] (/home/runner/rexom-1/node_modules/ejs/lib/ejs.js:489:10)
    at View.render (/home/runner/rexom-1/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/runner/rexom-1/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/runner/rexom-1/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/runner/rexom-1/node_modules/express/lib/response.js:1012:7)
    at /home/runner/rexom-1/source/server/routes/root-routes.js:17:9
    at Layer.handle [as handle_request] (/home/runner/rexom-1/node_modules/express/lib/router/layer.js:95:5)

**Comment by N1R0tka** [comment]
لو محت تأكد ان البوت سوا لوج ان بدون اي مشاكل
